name: Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [  ]

jobs:
  grafana-oss-mqtt-datasource:
    env:
      DOCKER_TAG_COMMON: gordlea/grafana-oss-mqtt-datasource
      DOCKER_CONTEXT_PATH: ./images/grafana-oss-mqtt-datasource
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 100
    - name: Look for changes
      id: grafanaossmqtt
      uses: YassinEldeeb/has-changed-path@v2.1
      with:
        paths: ${{ env.DOCKER_CONTEXT_PATH }}
    - name: Login to docker hub
      uses: docker/login-action@v1.14.1
      if: steps.grafanaossmqtt.outputs.changed == 'true' && github.event_name != 'pull_request'
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PAT }}
    - name: Determine new semver
      if: steps.grafanaossmqtt.outputs.changed == 'true'
      run: echo "SEMVER_TAG=$(tac ${DOCKER_CONTEXT_PATH}/Dockerfile | grep -m1 FROM | sed 's/FROM grafana\/grafana-oss://')" >> $GITHUB_ENV
    - name: Generate docker labels and tags
      id: meta
      if: steps.grafanaossmqtt.outputs.changed == 'true' && github.event_name != 'pull_request'
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        images: |
          ${{ env.DOCKER_TAG_COMMON }}
        # generate Docker tags based on the following events/attributes
        tags: |
          type=semver,pattern={{version}},value=${{ env.SEMVER_TAG }}
        labels: |
            maintainer=gordlea
            org.opencontainers.image.title=gordlea/grafana-oss-mqtt-datasource
            org.opencontainers.image.description=A grafana image based off the offical one with the mqtt-datasource plugin included
            org.opencontainers.image.url=https://github.com/gordlea/docker-images/images/grafana-oss-mqtt-datasource
            org.opencontainers.image.url=https://github.com/gordlea/docker-images/images/grafana-oss-mqtt-datasource

    - name: Setup docker buildx
      if: steps.grafanaossmqtt.outputs.changed == 'true'
      uses: docker/setup-buildx-action@v1.6.0

    - name: Build and push if main branch
      if: steps.grafanaossmqtt.outputs.changed == 'true'
      uses: docker/build-push-action@v2
      with:
        context: "${{env.DOCKER_CONTEXT_PATH}}"
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
