name: Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [  ]

jobs:

  build:
    env:
      DOCKER_CONTEXT_PATH: ./images/grafana-oss-mqtt-datasource
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - name: Docker Login
    #   uses: docker/login-action@v1.14.1
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_PAT }}
    - name: Determine Image Version
      run: tac ${DOCKER_CONTEXT_PATH}/Dockerfile | grep -m1 FROM | sed 's/FROM grafana\/grafana-oss://'
    # - name: Determine Image Version
    #   run: echo "GRAFANA_OSS_VERSION_TAG=$(tac ./Dockerfile | grep -m1 FROM | sed 's/FROM grafana\/grafana-oss://')" >> $GITHUB_ENV
    # - name: Show Image Version
    #   run: echo "$GRAFANA_OSS_VERSION_TAG"

    # - name: Build the Docker image
    #   run: |
    #     docker build ./images/grafana-oss-mqtt-datasource \
    #       --file ./images/grafana-oss-mqtt-datasource/Dockerfile \
    #       --tag docker.io/gordlea/grafana-oss-mqtt-datasource:latest
    #     docker tag docker.io/gordlea/grafana-oss-mqtt-datasource:latest docker.io/gordlea/grafana-oss-mqtt-datasource:{{ env.GRAFANA_OSS_VERSION_TAG}}
